name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: |
          cargo build --verbose
          cargo test --verbose
          cargo clippy -- -D warnings
          cargo fmt -- --check
